ClinicSystem.WebApplication/Models/MedicineViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ClinicSystem.Infrastructure.Dtos;
using ClinicSystem.Infrastructure.Model;

namespace ClinicSystem.WebApplication.Models
{
    public class MedicineIndexViewModel
    {
        public IEnumerable<MedicineDto> MedicineDtos { get; set; }
    }

    public class AddMedicineTypeViewModel
    {
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Nazwa'")]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Aktywny składnik'")]
        [Display(Name = "Aktywny składnik")]
        public string ActiveIngredient { get; set; }
    }

    public class AddMedicineViewModel
    {
        public IEnumerable<MEDICINE_TYPE> MedicineTypes { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Typ'")]
        [Display(Name = "Typ")]
        public long MedicineTypeId { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Seria'")]
        [Display(Name = "Seria")]
        public string BatchSeries { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Cena'")]
        [Display(Name = "Cena")]
        public decimal? Cost { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Data przydatności'")]
        [Display(Name = "Data przydatności")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ExpirationDate { get; set; }
    }
}

ClinicSystem.WebApplication/Controllers/MedicineController.cs
using System;
using System.Web.Mvc;
using ClinicSystem.Infrastructure.Model;
using ClinicSystem.WebApplication.Interfaces;
using ClinicSystem.WebApplication.Models;

namespace ClinicSystem.WebApplication.Controllers
{
    public class MedicineController : Controller
    {
        private readonly IMedicineRepository _medicineRepository;

        public MedicineController(IMedicineRepository medicineRepository)
        {
            _medicineRepository = medicineRepository;
        }

        [Authorize(Roles = "ADMINISTRATOR, MANAGER, DOCTOR")]
        // GET: Medicine
        public ActionResult Index(MedicineMessageId? message)
        {
            ViewBag.StatusMessage = 
                message == MedicineMessageId.AddMedicineSuccess ? "Poprawnie dodano lek" :
                message == MedicineMessageId.AddMedicineTypeSuccess ? "Poprawnie dodano typ leku" : 
                "";

            var model = new MedicineIndexViewModel
            {
                MedicineDtos = _medicineRepository.GetAllMedicineDtos()
            };

            return View(model);
        }

        public ActionResult AddMedicineType()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMedicineType(AddMedicineTypeViewModel model)
        {
            var medicineType = new MEDICINE_TYPE
            {
                LAST_MOD_DATE = DateTime.Now,
                MEDICINE_NAME = model.Name,
                ACTIVE_INGREDIENT = model.ActiveIngredient
            };

            _medicineRepository.CreateMedicineType(medicineType);

            return RedirectToAction("Index", new { Message = MedicineMessageId.AddMedicineTypeSuccess });
        }

        public ActionResult AddMedicine()
        {
            var model = new AddMedicineViewModel
            {
                MedicineTypes = _medicineRepository.GetAllMedicineTypes()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddMedicine(AddMedicineViewModel model)
        {
            var medicine = new MEDICINE_ORDER
            {
                LAST_MOD_DATE = DateTime.Now,
                MEDICINE_TYPE_ID = model.MedicineTypeId,
                MEDICINE_BATCH_SERIES = model.BatchSeries,
                COST = model.Cost ?? 0,
                EXPIRE_DATE = model.ExpirationDate ?? DateTime.MaxValue
            };

            _medicineRepository.CreateMedicine(medicine);

            return RedirectToAction("Index", new { Message = MedicineMessageId.AddMedicineSuccess });
        }

        public enum MedicineMessageId
        {
            AddMedicineSuccess,
            AddMedicineTypeSuccess
        }
    }
}

ClinicSystem.WebApplication/Views/Medicine/AddMedicine.cshtml
@model ClinicSystem.WebApplication.Models.AddMedicineViewModel

@{
    ViewBag.Title = "Dodaj lek";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddMedicine", "Medicine", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Formularz dodawania nowego leku</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.MedicineTypeId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.MedicineTypeId,
                new SelectList(Model.MedicineTypes, "ID", "MEDICINE_NAME"),
                "Wybierz typ leku...",
                new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BatchSeries, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.BatchSeries, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cost, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Cost, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ExpirationDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ExpirationDate, new { @class = "datepicker, form-control", @type = "date" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Medicine/AddMedicineType.cshtml
@model ClinicSystem.WebApplication.Models.AddMedicineTypeViewModel

@{
    ViewBag.Title = "Dodaj typ leku";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddMedicineType", "Medicine", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Formularz dodawania nowego typu leku</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ActiveIngredient, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ActiveIngredient, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Medicine/Index.cshtml
@using GridMvc.Html
@model ClinicSystem.WebApplication.Models.MedicineIndexViewModel

@{
    ViewBag.Title = "Lekarstwa";
}

<h2>@ViewBag.Title</h2>
<p class="text-success">@ViewBag.StatusMessage</p>
<div>
    <h4>Zarządzanie danymi lekarstw</h4>
    <hr />
    @Html.Grid(Model.MedicineDtos.ToList()).Columns(columns =>
{
    columns.Add(c => c.Name).Titled("Nazwa");
    columns.Add(c => c.ActiveIngredient).Titled("Składniki");
    columns.Add(c => c.Cost).Titled("Cena");
    columns.Add(c => c.BatchSeries).Titled("Seria");
    columns.Add(c => c.ExpirationDate).Titled("Data przydatności").Format("{0:dd.MM.yyyy}"); ;
    columns.Add(c => c.Amount).Titled("Ilość");
}).WithPaging(10).Sortable(true).Filterable(true)
    <br/>
    <h4>Operacje:</h4>
    @Html.ActionLink("Dodaj lek", "AddMedicine", "Medicine", htmlAttributes: new { @class = "btn btn-primary", @role = "button" })
    @Html.ActionLink("Dodaj typ leku", "AddMedicineType", "Medicine", htmlAttributes: new { @class = "btn btn-primary", @role = "button" })
</div>