ClinicSystem.WebApplication/Models/ExaminationViewModels.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ClinicSystem.Infrastructure.Dtos;
using ClinicSystem.Infrastructure.Model;

namespace ClinicSystem.WebApplication.Models
{
    public class ExaminationIndexViewModel
    {
        public string UnitName { get; set; }
        public IEnumerable<VisitDto> UnitVisitDtos { get; set; }
        public IEnumerable<VisitDto> PatientVisitDtos { get; set; }
        public IEnumerable<PATIENT_DIAGNOSE> PatientDiagnoses { get; set; }
    }

    public class VisitDetailsViewModel
    {
        public VisitDto VisitDto { get; set; }
        public IEnumerable<PATIENT_DIAGNOSE> PatientDiagnoses { get; set; }
        public IEnumerable<DIAGNOSTICS> Diagnostics { get; set; }
        public IEnumerable<PATIENT_MEDICINES> Medicines { get; set; }
    }

    public class AddDiagnoseViewModel
    {
        public long VisitId { get; set; }
        public IEnumerable<DISEASE> Diseases { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Choroba'")]
        [Display(Name = "Choroba")]
        public long DiseaseId { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Diagnoza'")]
        [Display(Name = "Diagnoza")]
        public string Diagnose { get; set; }
    }

    public class AddExaminationViewModel
    {
        public long VisitId { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Nazwa badania'")]
        [Display(Name = "Nazwa badania")]
        public string ExaminationName { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Koszt'")]
        [Display(Name = "Koszt")]
        public decimal Cost { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Data badania'")]
        [Display(Name = "Data badania")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ExaminationDate { get; set; }
    }

    public class AddPatientMedicineViewModel
    {
        public long VisitId { get; set; }
        public IEnumerable<MedicineDto> MedicineDtos { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Lek'")]
        [Display(Name = "Lek")]
        public long TypeId { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Dawkowanie'")]
        [Display(Name = "Dawkowanie")]
        public string Dose { get; set; }
        [Required(ErrorMessage = "Wprowadź wartość w polu 'Data leczenia'")]
        [Display(Name = "Data leczenia")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? TreatmentDate { get; set; }
    }
}

ClinicSystem.WebApplication/Controllers/ExaminationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ClinicSystem.Infrastructure.Model;
using ClinicSystem.WebApplication.Interfaces;
using ClinicSystem.WebApplication.Models;

namespace ClinicSystem.WebApplication.Controllers
{
    public class ExaminationController : Controller
    {
        private readonly IExaminationRepository _examinationRepository;
        private readonly IExaminationValidationService _validationService;
        
        public ExaminationController(IExaminationRepository examinationRepository, IExaminationValidationService validationService)
        {
            _examinationRepository = examinationRepository;
            _validationService = validationService;
        }

        [Authorize]
        public ActionResult Index()
        {
            var person = _examinationRepository.GetLoggedPersonByUserName(User.Identity.Name);
            var model = new ExaminationIndexViewModel();

            if (person != null)
            {
                var employee = _examinationRepository.GetEmployeeByPersonId(person.ID);
                if (employee != null)
                {
                    model.UnitName = employee.UNIT.UNIT_TYPE.UNIT_NAME + ", " + employee.UNIT.CLINIC.NAME + " " +
                                     employee.UNIT.CLINIC.ADDRESS;
                    model.UnitVisitDtos = _examinationRepository.GetUnitVisitDtosByUnitId(employee.UNIT_ID);
                    model.PatientDiagnoses = _examinationRepository.GetPatientDiagnosesByUnitId(employee.UNIT_ID);
                }
                else
                {
                    model.PatientVisitDtos = _examinationRepository.GetPatientVisitDtos(person.ID);
                    model.PatientDiagnoses = _examinationRepository.GetPatientDiagnosesByPersonId(person.ID);
                }
            }
            else
            {
                model.UnitVisitDtos = _examinationRepository.GetAllVisitDtos();
                model.PatientDiagnoses = _examinationRepository.GetAllPatientDiagnoses();
            }

            return View(model);
        }

        public ActionResult VisitDetails(long visitId, ExaminationMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ExaminationMessageId.AddExaminationSuccess ? "Poprawnie dodano badanie" :
                message == ExaminationMessageId.AddExaminationFail ? "Nie udało się dodać badania - wybrany oddział przychodni nie posiada planu budżetowego dla wskazanej daty badania" :
                message == ExaminationMessageId.AddDiagnoseSuccess ? "Poprawnie dodano diagnozę" :
                message == ExaminationMessageId.AddPatientMedicineSuccess ? "Poprawnie przepisano lekarstwa" :
                    "";

            var model = new VisitDetailsViewModel
            {
                VisitDto = _examinationRepository.GetVisitDtoByVisitId(visitId),
                Diagnostics = _examinationRepository.GetDiagnosticsByPatientVisitId(visitId),
                PatientDiagnoses = _examinationRepository.GetPatientDiagnosesByPatientVisitId(visitId),
                Medicines = _examinationRepository.GetPatientMedicinesByPatientVisitId(visitId)
            };

            return View(model);
        }

        public ActionResult AddDiagnose(long visitId)
        {
            var model = new AddDiagnoseViewModel
            {
                VisitId = visitId,
                Diseases = _examinationRepository.GetAllDiseases()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddDiagnose(AddDiagnoseViewModel model)
        {
            _examinationRepository.CreateDiagnose(model.VisitId, model.DiseaseId, model.Diagnose);

            return RedirectToAction("VisitDetails",
                routeValues: new { visitId = model.VisitId, message = ExaminationMessageId.AddDiagnoseSuccess });
        }

        public ActionResult AddExamination(long visitId)
        {
            var model = new AddExaminationViewModel
            {
                VisitId = visitId
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddExamination(AddExaminationViewModel model)
        {
            var person = _examinationRepository.GetLoggedPersonByUserName(User.Identity.Name);

            var employee = person != null
                ? _examinationRepository.GetEmployeeByPersonId(person.ID)
                : null;

            if (_validationService.IsUnitPlanValid(model.VisitId, model.ExaminationDate.GetValueOrDefault()))
            {
                _examinationRepository.CreateExamination(model.ExaminationName,
                    model.ExaminationDate.GetValueOrDefault(),
                    model.Cost, model.VisitId, employee);
            }
            else
            {
                return RedirectToAction("VisitDetails",
                    routeValues: new { visitId = model.VisitId, message = ExaminationMessageId.AddExaminationFail });
            }

            return RedirectToAction("VisitDetails",
                routeValues: new { visitId = model.VisitId, message = ExaminationMessageId.AddExaminationSuccess });
        }

        public ActionResult AddPatientMedicine(long visitId)
        {
            var model = new AddPatientMedicineViewModel
            {
                VisitId = visitId,
                MedicineDtos = _examinationRepository.GetAllMedicineDtos()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AddPatientMedicine(AddPatientMedicineViewModel model)
        {
            _examinationRepository.CreatePatientMedicine(model.TypeId, model.Dose,
                model.TreatmentDate.GetValueOrDefault(), model.VisitId);

            return RedirectToAction("VisitDetails",
                routeValues: new { visitId = model.VisitId, message = ExaminationMessageId.AddPatientMedicineSuccess });
        }

        public enum ExaminationMessageId
        {
            AddExaminationSuccess,
            AddExaminationFail,
            AddDiagnoseSuccess,
            AddPatientMedicineSuccess
        }
    }
}

ClinicSystem.WebApplication/Views/Examination/AddDiagnose.cshtml
@model ClinicSystem.WebApplication.Models.AddDiagnoseViewModel

@{
    ViewBag.Title = "Diagnozuj";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddDiagnose", "Examination", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Wystaw diagnozę dla pacjenta</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.VisitId)
    <div class="form-group">
        @Html.LabelFor(m => m.DiseaseId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.DiseaseId,
                new SelectList(Model.Diseases, "ID", "CODE"),
                "Wybierz chorobę...",
                new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Diagnose, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Diagnose, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Examination/AddDisease.cshtml
@model ClinicSystem.WebApplication.Models.AddDiseaseViewModel

@{
    ViewBag.Title = "Dodaj chorobę do słownika";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddDisease", "Examination", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Formularz dodawania nowej przychodni</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Examination/AddExamination.cshtml
@model ClinicSystem.WebApplication.Models.AddExaminationViewModel

@{
    ViewBag.Title = "Dodaj badanie";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddExamination", "Examination", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Formularz dodawania badania</h4>
    <hr />
    @Html.HiddenFor(m => m.VisitId)
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.ExaminationName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ExaminationName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ExaminationDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ExaminationDate, "{0:yyyy-MM-ddThh:mm:ss}", new { @class = "form-control", type = "datetime-local" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cost, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Cost, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Examination/AddPatientMedicine.cshtml
@model ClinicSystem.WebApplication.Models.AddPatientMedicineViewModel

@{
    ViewBag.Title = "Przepisz lekarstwo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddPatientMedicine", "Examination", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Formularz przepisywania leku dla pacjenta</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.VisitId)
    <div class="form-group">
        @Html.LabelFor(m => m.TypeId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.TypeId,
                new SelectList(Model.MedicineDtos, "TypeId", "Name"),
                "Wybierz lek...",
                new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Dose, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Dose, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TreatmentDate, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.TreatmentDate, new { @class = "datepicker, form-control", @type = "date" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Zapisz" class="btn btn-default" />
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicSystem.WebApplication/Views/Examination/Index.cshtml
@using GridMvc.Html
@model ClinicSystem.WebApplication.Models.ExaminationIndexViewModel

@{
    ViewBag.Title = "Wizyty i badania";
}

<h2>@ViewBag.Title</h2>
<p class="text-success">@ViewBag.StatusMessage</p>
<div>
    <h4>Zarządzanie danymi wizyt i badań</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (User.IsInRole("DOCTOR") || User.IsInRole("ADMINISTRATOR") || User.IsInRole("MANAGER"))
        {
            <dd>
                <br />
            </dd>
            if (!string.IsNullOrEmpty(Model.UnitName))
            {
                <dt>Wizyty na oddziale @Model.UnitName:</dt>
            }
            else
            {
                <dt>Wizyty na wszystkich oddziałach:</dt>
            }
            <dd>
                @if (Model.UnitVisitDtos.Any())
                {
                    @Html.Grid(Model.UnitVisitDtos).Columns(columns =>
               {
                   columns.Add(c => c.DateFrom).Titled("Data od").Format("{0:dd.MM.yyyy HH:mm}");
                   columns.Add(c => c.DateTo).Titled("Data do").Format("{0:dd.MM.yyyy HH:mm}");
                   columns.Add(c => c.PersonName).Titled("Pacjent");
                   columns.Add(c => c.PersonPesel).Titled("PESEL");
                   columns.Add(c => c.PersonAddress).Titled("Adres pacjenta");
                   columns.Add().Sanitized(false).Encoded(false).RenderValueAs(visit => Html.ActionLink("Szczegóły", "VisitDetails", new { visitId = visit.Id }, null).ToHtmlString());
               }).WithPaging(10).Sortable(true).Filterable(true)
                }
                else
                {
                    <p>Brak</p>
                }
            </dd>
        }
        else if (User.IsInRole("PATIENT"))
        {
            <dt>Moje wizyty:</dt>
            <dd>
                @if (Model.PatientVisitDtos.Any())
                {
                    @Html.Grid(Model.PatientVisitDtos).Columns(columns =>
               {
                   columns.Add(c => c.DateFrom).Titled("Data od").Format("{0:dd.MM.yyyy HH:mm}"); 
                   columns.Add(c => c.DateTo).Titled("Data do").Format("{0:dd.MM.yyyy HH:mm}");
                   columns.Add(c => c.PersonPesel).Titled("PESEL");
                   columns.Add(c => c.PersonAddress).Titled("Mój adres");
                   columns.Add(c => c.ClinicNameAndAddress).Titled("Nazwa i adres przychodni");
                   columns.Add().Sanitized(false).Encoded(false).RenderValueAs(visit => Html.ActionLink("Szczegóły", "VisitDetails", new { visitId = visit.Id }, null).ToHtmlString());
               }).WithPaging(10).Sortable(true).Filterable(true)
                }
                else
                {
                    <p>Brak</p>
                }
            </dd>
        }
        <dd>
            <br />
        </dd>
        <dt>Moje diagnozy:</dt>
        <dd>
            @if (Model.PatientDiagnoses.Any())
            {
                @Html.Grid(Model.PatientDiagnoses.ToList()).Columns(columns =>
                {
                    columns.Add(c => c.DIAGNOSE).Titled("Diagnoza");
                    columns.Add(c => c.DISEASE.CODE).Titled("Choroba");
                    columns.Add(c => c.PATIENT_VISIT.CLINIC.NAME).Titled("Nazwa przychodni");
                    columns.Add(c => c.PATIENT_VISIT.CLINIC.ADDRESS).Titled("Adres przychodni");
                }).WithPaging(10).Sortable(true).Filterable(true)
            }
            else
            {
                <p>Brak</p>
            }
        </dd>
    </dl>
</div>

ClinicSystem.WebApplication/Views/Examination/VisitDetails.cshtml
@model ClinicSystem.WebApplication.Models.VisitDetailsViewModel

@{
    ViewBag.Title = "Szczegóły wizyty";
}

<h2>@ViewBag.Title</h2>
<p class="text-success">@ViewBag.StatusMessage</p>
<div>
    <h4>Dane wizyty:</h4>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Imię i nazwisko</th>
                <th>Adres</th>
                <th>PESEL</th>
                <th>Data rozpoczęcia wizyty</th>
                <th>Data zakończenia wizyty</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.VisitDto.PersonName</td>
                <td>@Model.VisitDto.PersonAddress</td>
                <td>@Model.VisitDto.PersonPesel</td>
                <td>@Model.VisitDto.DateFrom.ToString("dd.MM.yyyy HH:mm")</td>
                <td>@Model.VisitDto.DateTo.ToString("dd.MM.yyyy HH:mm")</td>
            </tr>
        </tbody>
    </table>
    <hr />
    <h4>Diagnozy:</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Diagnoza</th>
                <th>Choroba</th>
                <th>Opis choroby</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var patientDiagnose in Model.PatientDiagnoses)
            {
                <tr>
                    <td>@patientDiagnose.DIAGNOSE</td>
                    <td>@patientDiagnose.DISEASE.CODE</td>
                    <td>@patientDiagnose.DISEASE.CODE_DESCRIPTION</td>
                </tr>
            }
        </tbody>
    </table>
    <h4>Badania:</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nazwa badania</th>
                <th>Koszt</th>
                <th>Wykonujący badanie</th>
                <th>Data badania</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var diagnostic in Model.Diagnostics)
            {
                <tr>
                    <td>@diagnostic.EXAMINATION.EXAMINATION_NAME</td>
                    <td>@diagnostic.EXAMINATION.COST</td>
                    <td>@(diagnostic.EMPLOYEE.PERSON.NAME + " " + diagnostic.EMPLOYEE.PERSON.LAST_NAME)</td>
                    <td>@diagnostic.EXAMINATION_DATE.ToString("dd.MM.yyyy")</td>
                </tr>
            }
        </tbody>
    </table>
    <h4>Przepisane leki:</h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Dawka</th>
                <th>Data leczenia</th>
                <th>Nazwa</th>
                <th>Składniki</th>
                <th>Koszt</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var medicine in Model.Medicines)
            {
                <tr>
                    <td>@medicine.DOSE</td>
                    <td>@medicine.TREATMENT_DATE.ToString("dd.MM.yyyy")</td>
                    <td>@medicine.MEDICINE_ORDER.MEDICINE_TYPE.MEDICINE_NAME</td>
                    <td>@medicine.MEDICINE_ORDER.MEDICINE_TYPE.ACTIVE_INGREDIENT</td>
                    <td>@medicine.MEDICINE_ORDER.COST</td>
                </tr>
            }
        </tbody>
    </table>
    @if (User.IsInRole("DOCTOR") || User.IsInRole("ADMINISTRATOR") || User.IsInRole("MANAGER"))
    {
        <hr />
        <h4>Operacje:</h4>
        <br />
        @Html.ActionLink("Diagnozuj", "AddDiagnose", "Examination", routeValues: new { visitId = Model.VisitDto.Id }, htmlAttributes: new { @class = "btn btn-primary", @role = "button" })
        <br />
        <br />
        @Html.ActionLink("Wykonaj badanie", "AddExamination", "Examination", routeValues: new { visitId = Model.VisitDto.Id }, htmlAttributes: new { @class = "btn btn-primary", @role = "button" })
        <br />
        <br />
        @Html.ActionLink("Przepisz lekarstwo", "AddPatientMedicine", "Examination", routeValues: new { visitId = Model.VisitDto.Id }, htmlAttributes: new { @class = "btn btn-primary", @role = "button" })
    }
</div>